name: Run unit tests

on: push

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3.4.0

      - name: Run tests
        run: yarn install && yarn workspaces run test
